all:
  vars:
    ansible_port: 2002
    ansible_user: basit.shaukat
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    livestream5:
      ansible_host: 203.82.48.74
    livestream6:
      ansible_host: 203.99.50.70
    nayatvfe01:
      ansible_host: 115.186.184.197
    nayatvfe02:
      ansible_host: 115.186.184.198
    nayatvfe03:
      ansible_host: 115.186.184.199
    nayatvfe04:
      ansible_host: 202.165.249.244
    nayatvfe05:
      ansible_host: 202.165.249.246
    nayatvfe06:
      ansible_host: 202.165.249.248
    nayatvfe07:
      ansible_host: 115.186.184.200
    livestreamfsd:
      ansible_host: 45.115.85.134
    livestreamfsdbkp:
      ansible_host: 103.55.69.214
    livestreamlhr:
      ansible_host: 101.50.114.34
    nayatvfe1-new:
      ansible_host: 203.175.74.69
    nayatvfe2-new:
      ansible_host: 115.186.184.178
    nayatvbenew:
      ansible_host: 58.65.169.84
    nayatvbe2new:
      ansible_host: 58.65.169.85
    streambe1.nayatel.com:
      ansible_host: 172.16.179.189
    streambe2.nayatel.com:
      ansible_host: 172.16.250.34
    streamfe1.nayatel.com:
      ansible_host: 202.165.249.211
    streamfe2.nayatel.com:
      ansible_host: 202.165.249.204
  children:
    nayatv_live:
      hosts:
        livestream5:
        livestream6:
        nayatvfe01:
        nayatvfe02:
        nayatvfe03:
        nayatvfe04:
        nayatvfe05:
        nayatvfe06:
        nayatvfe07:
        nayatvfe1-new:
        nayatvfe2-new:
        nayatvbenew:
        nayatvbe2new:
    vod:
      hosts:
        streambe1.nayatel.com:
        streambe2.nayatel.com:
        streamfe1.nayatel.com:
        streamfe2.nayatel.com:
    test:
      hosts:
        livestream5:
    test2:
      hosts:
        nayatvfe07:
        nayatvfe06:
        livestream5: 
